apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -dev
patches:
  - path: deployment-patch.yaml
  - path: hpa-patch.yaml
configMapGenerator:
  - name: finops-optimizer-config
    behavior: merge
    literals:
      - APP_ENV=development
      - MINIMUM_SAVINGS_USD=1
images:
  - name: ghcr.io/muratmiracg-dev/huawei-finops-optimizer
    newTag: edge
