apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "finops-optimizer.fullname" . }}
  labels:
    {{- include "finops-optimizer.labels" . | nindent 4 }}
    finops.huaweicloud.com/cost-center: {{ .Values.finopsLabels.costCenter | quote }}
    finops.huaweicloud.com/owner: {{ .Values.finopsLabels.owner | quote }}
    finops.huaweicloud.com/environment: {{ .Values.finopsLabels.environment | quote }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "finops-optimizer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "finops-optimizer.selectorLabels" . | nindent 8 }}
        finops.huaweicloud.com/cost-center: {{ .Values.finopsLabels.costCenter | quote }}
        finops.huaweicloud.com/owner: {{ .Values.finopsLabels.owner | quote }}
        finops.huaweicloud.com/environment: {{ .Values.finopsLabels.environment | quote }}
    spec:
      serviceAccountName: {{ include "finops-optimizer.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "finops-optimizer.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /health/live
              port: http
            failureThreshold: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 64Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
